name: Tests

on: [push, pull_request]

jobs:
  test:
    name: Ruby ${{ matrix.ruby }}, Rails ${{ matrix.rails }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: [3.1, '3.0']
        rails: ['7.0.0']

    env:
      RAILS_VERSION: ${{ matrix.rails }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # 'bundle install' and cache
    - name: Run tests
      run: bundle exec rake
